[package]
name = "cr_epi"
version = "0.1.0"
edition = "2021"

[dependencies]
crunchyroll-rs = "0.12"
tokio = { version = "1", features = ["full"] }
openssl = { version = "0.10", features = ["vendored"] }

[[bin]]
name = "cr_epi"
path = "main.rs"
